name: Publish Docker image (HEAD)
on:
  push:
    branches: [main, oscar/docker]
    tags: grain-v*.*.*
jobs:
  push_base_image:
    name: Push base Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Parse tag
        # This step converts Grain tags into standard semver, i.e. grain-v1.2.3 -> v1.2.3
        id: vars
        if: ${{ github.ref_type == 'tag' }}
        run: echo ::set-output name=tag::${'{{ github.ref_name }}'#grain-}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            grainlang/grain
            ghcr.io/grain-lang/grain
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ steps.vars.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.vars.outputs.tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_slim_image:
    name: Push slim Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Parse tag
        # This step converts Grain tags into standard semver, i.e. grain-v1.2.3 -> v1.2.3
        id: vars
        if: ${{ github.ref_type == 'tag' }}
        run: echo ::set-output name=tag::${'{{ github.ref_name }}'#grain-}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          flavor: |
            suffix=-slim,onlatest=true
          images: |
            grainlang/grain
            ghcr.io/grain-lang/grain
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ steps.vars.outputs.tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.vars.outputs.tag }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push slim image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-slim
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
